name = "glep"
version = "1.0.0"
description = "A grep-like CLI tool written in Gleam."
licences = ["MIT"]
repository = { type = "github", user = "finndotbin", repo = "glep" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
chromatic = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
